"""Remove text field from Logo model

Revision ID: 2354d9068b01
Revises: a744f97ec7a8
Create Date: 2024-12-31 08:05:32.819245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2354d9068b01'
down_revision = 'a744f97ec7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logos', schema=None) as batch_op:
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
