"""Add title and intro to Name model

Revision ID: 693e8d77712b
Revises: 19eafe513126
Create Date: 2024-12-30 23:21:34.459104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693e8d77712b'
down_revision = '19eafe513126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('intro', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('names')
    # ### end Alembic commands ###
